# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diff-openapi-spec:
    runs-on: ubuntu-latest

    steps:
      - name: Check out PR branch
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
            architecture: 'x64'
      - name: Generate OpenAPI spec from the application
        run: |
          pip install -e .
          npm i .
          cp specs/openreferee.yaml specs/openreferee.old.yaml
          npm run api-spec
      - name: Set up env variables
        run:  |
          echo "::set-env name=ORIGIN_SPEC::$(echo "$(pwd)/specs/openreferee.old.yaml" )"
          echo "::set-env name=MODIFIED_SPEC::$(echo "$(pwd)/specs/openreferee.yaml" )"
          echo "::set-env name=DIFF_FILE::$(echo "$(pwd)/openapi.diff" )"
      - name: Generate report
        run: |
          if ! diff -u ${{ env.ORIGIN_SPEC }} ${{ env.MODIFIED_SPEC }} > ${{ env.DIFF_FILE }};
          then
            COMMENT_FILE=$(echo "$(pwd)/github-comment.md")
            echo "::set-env name=GH_COMMENT_FILE::${COMMENT_FILE}"
            printf ":warning: There are differences between the generated spec and the app" > ${COMMENT_FILE}
            printf "\n\n\`\`\`diff\n" >> ${COMMENT_FILE}
            cat ${{ env.DIFF_FILE }} >> ${COMMENT_FILE}
            printf "\n\`\`\`\n" >> ${COMMENT_FILE}
          fi
      - name: comment PR
        if: ${{ env.GH_COMMENT_FILE }}
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: github-comment.md
