# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diff-openapi-spec:
    runs-on: ubuntu-latest

    steps:
      - name: Check out master branch
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
            architecture: 'x64'
      - name: Generate OpenAPI spec from the application
        run: |
          pip install -e .
          npm i .
          cp spec/openreferee.yaml spec/openreferee.old.yaml
          npm run api-spec
      - name: Run OpenAPI Diff (from HEAD revision)
        uses: evereepay/openapi-diff-action@v1.0.0-beta.2
        with:
          head-spec: spec/openreferee.yaml
          base-spec: spec/openreferee.old.yaml
          github-token: ${{ github.token }}
